# Generated by Django 6.0.6 on 2026-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(help_text='Enter Address'),
        ),
    ]
