# Generated by Django 6.0.6 on 2026-08-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_category_food_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Category',
            new_name='category',
        ),
    ]
